import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

const AdminLevels = [
  { value: "super_admin", label: "Super Admin (All Access)" },
  { value: "admin_level_1", label: "Admin Level 1 (Add Trainer/TPO/Activity)" },
  { value: "admin_level_2", label: "Admin Level 2 (Add Trainer/Activity)" },
  { value: "admin_level_3", label: "Admin Level 3 (View Activity Only)" }
];

function AddAdmin() {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [role, setRole] = useState("admin_level_3");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const submitHandler = async (e) => {
    e.preventDefault();
    setError("");
    setSuccess("");
    setLoading(true);

    const token = localStorage.getItem("adminToken");

    try {
      const response = await fetch('/api/admin/add-admin', {
        method: "POST",
        headers: { 
          "Content-Type": "application/json", 
          Authorization: `Bearer ${token}` 
        },
        body: JSON.stringify({ email, role }) // password autogenerated by backend
      });

      const data = await response.json();

      if (data.success) {
        setSuccess("Admin added successfully; login credentials sent via email.");
        setEmail("");
        setRole("admin_level_3");
      } else {
        setError(data.message || "Failed to add admin");
      }
    } catch {
      setError("Request failed");
    }

    setLoading(false);
  };

  return (
    <div className="max-w-md mx-auto mt-10 p-6 bg-white rounded shadow">
      <h2 className="text-2xl font-semibold mb-6">Add New Admin</h2>
      <form onSubmit={submitHandler} className="space-y-4">
        <input
          type="email"
          placeholder="Email"
          required
          value={email}
          onChange={e => setEmail(e.target.value)}
          className="w-full border rounded px-3 py-2"
          autoComplete="username"
        />
        <select
          value={role}
          onChange={e => setRole(e.target.value)}
          className="w-full border rounded px-3 py-2"
          aria-label="Select Admin Role"
        >
          {AdminLevels.map(({ value, label }) => (
            <option key={value} value={value}>{label}</option>
          ))}
        </select>
        {error && <p className="text-red-600">{error}</p>}
        {success && <p className="text-green-600">{success}</p>}
        <button
          type="submit"
          disabled={loading}
          className="w-full py-2 font-semibold text-white bg-indigo-600 rounded hover:bg-indigo-700"
        >
          {loading ? "Adding..." : "Add Admin"}
        </button>
        <button
          type="button"
          onClick={() => navigate(-1)}
          className="w-full mt-2 py-2 rounded bg-gray-200 hover:bg-gray-300"
        >
          Cancel
        </button>
      </form>
    </div>
  );
}

export default AddAdmin;
